splits: ???
ids: ???
data_path: ${root:data/interim/sgd}

defaults:
  - conversation_builder: mine_user_slot_confirmations
  - _self_

output_path: 'resources/mining_results/user_slot_confirmations'

hydra:
  run:
    dir: "${...output_path}"

run_dir: ${root:${hydra:run.dir}}
