splits: ???
ids: ???
data_path: ${root:data/interim/sgd}

defaults:
  - conversation_builder: mine_offered_slots
  - _self_

output_path: 'resources/mining_results/multiple_values_offered_actions'

hydra:
  run:
    dir: "${...output_path}"

run_dir: ${root:${hydra:run.dir}}
