splits: ???
ids: ???
data_path: ${root:data/raw/sgd}
index_path: ${root:resources/sgd/index}
defaults:
  - conversation_builder: mine_request_parametrisation
  - _self_

output_path: 'resources/mining_results/parametrised_requests_metadata'

hydra:
  run:
    dir: "${...output_path}"

run_dir: ${root:${hydra:run.dir}}
