defaults:
  - pytod/pytod_formatter@formatter: default
  - _self_

split: ???
ids: ~
debug: false
exclude_ids: []
version: ???
# if `true`, the resume instructions
# copy attributes from history, which
# persist if the generated API call is wrong
lenient: false
sgd_variant: 'original'
experiment_name: ~
checkpoint: ~
hyps_dir: ${root:hyps}
metrics_dir: ${root:metrics}
data_path: ${root:data/processed/sgd/${version}}
save_shards: false

mapper:
  _target_: pytod.evaluation.evaluation_utils.SGDFileMapper
  template_dir: ${root:data/templates/sgd/${split}}
  dialogues_to_map: ${ids}
  corrections_info:
    _target_: pytod.utils.load_json
    _args_:
      - ${root:resources/corrections/utterances/${split}.json}

reference_files:
  _target_: pytod.evaluation.evaluation_utils.setup_sgd_evaluator_inputs
  ref_dir: ${root:data/interim/sgd/${split}}
  decoded_only: ${ids}

command_collection:
  _target_: pytod.command.CommandCollection
  schema_path: ${root:data/processed/sgd/${version}}/${split}/schema.json


conversation_builder:
  _target_: pytod.pytod_conversation_builder.pytod_transcript_builder
  _partial_: true

output_path: '${root:reports/evaluation}'

hydra:
  run:
    dir: ${...output_path}/${...split}/${experiment_name}/${sgd_variant}/${checkpoint}

wandb:
  run_id: ~
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}
  tags: []
