author: 'Hint'
# if `true`, a hint is displayed for each
# required slot yet to be filled by the user
multiple_slot_filling: false
# shuffle the list of hints shown to the model for
# action selection
randomise_hint_order: true
# grounds turns where the agent asks the user
# to provide information required for calling APIs
slot_filling_template:
  _target_: pytod.pytod_types.transcript.BackendHintTemplate
  dialog_template: "request value: {arg}{value_examples}"
  tag: 'slot_filling_hint'
  fields:
    - _target_: pytod.pytod_types.transcript.TemplateField
      field: 'arg'
      is_variable: false
    - _target_: pytod.pytod_types.transcript.TemplateField
      field: 'value_examples'
      is_variable: false
  is_assignable: true
  origin_template: '{current_call}'
  origin_fields:
    - _target_: pytod.pytod_types.transcript.TemplateField
      field: 'current_call'
      is_variable: true
# grounds turns where the agent asks the user to confirm
# their transaction (entity properties stated depend on
# whether the user corrects instead of confirming)
confirmation_template:
  _target_: pytod.pytod_types.transcript.BackendHintTemplate
  dialog_template: "ask the user to confirm: {entity_properties}"
  tag: 'require_confirmation_hint'
  fields:
    - _target_: pytod.pytod_types.transcript.TemplateField
      field: 'arg'
      is_variable: false
  pass_to_nlg: true
  is_assignable: true
  origin_template: '{current_call}'
  origin_fields:
    - _target_: pytod.pytod_types.transcript.TemplateField
      field: 'current_call'
      is_variable: true
# grounds turns where the agent offers an alternative arrangement
# to the user because the transaction they confirmed failed
results_alternative_template:
  _target_: pytod.pytod_types.transcript.BackendHintTemplate
  dialog_template: "alternative: {offer_params}"
  tag: 'offer_alternative_signal'
  fields:
    _target_: pytod.pytod_types.transcript.TemplateField
    field: 'offer_params'
    is_variable: false
  pass_to_nlg: true
  origin_template: '{current_call}'
  origin_fields:
    - _target_: pytod.pytod_types.transcript.TemplateField
      field: 'current_call'
      is_variable: true
# grounds turns whether the agent prompts the user to say if they
# need more help. This can happen:
#    - after a transactional intent is executed and the user does not state the next task or dismiss the agent
#    - co-ordinated with a `NOTIFY_FAILURE` dialogue act through which agent informs the user an API call failed.
prompt_more_help_required:
  _target_: pytod.pytod_types.transcript.BackendHintTemplate
  dialog_template: "ask the user if they require further assistance"
  tag: 'prompt_more_help_required'
  fields: []
  origin_template: '{current_call}'
  origin_fields:
    - _target_: pytod.pytod_types.transcript.TemplateField
      field: 'current_call'
      is_variable: true

# TODO: tidy up config, origin_template and origin_fields are repeated for all hints
