#
# For licensing see accompanying LICENSE file.
# Copyright © 2025 Apple Inc. All Rights Reserved.
#
from dataclasses import dataclass

from pytod.command import CommandCollection
from pytod.pytod_types.aliases import (
    DialogueID,
    ServiceName,
    SlotName,
    ToolName,
    VariableIdx,
)

from pytod.inference.schema_supervisor import SchemaSupervisor


@dataclass
class SchemaConstraintContext:
    """A context passed to the parser for constraining
    the expressions predicted by the language model
    according to the schema.

    Parameters
    ----------
    intent_predicted
        Whether a valid intent was predicted at the
        current turn
    slot_sim_threshold
        Generated slot names that are not identified as
        part of the intent schema are mapped to a slot in the
        schema if their Levenstein distance is above this
        threshold
    schema_slot_sim_threshold
        As above, but applied to arguments of other intents
        in the same service
    """

    last_user_turn_service: ServiceName
    schema: CommandCollection
    dial_id: DialogueID
    variable_mapping: dict[VariableIdx, ToolName]
    intent_predicted: bool
    slot_sim_threshold: float = 0.75
    schema_slot_sim_threshold: float = 0.9


@dataclass
class AssistantConstraintContext:
    """A context passed to the parser for constraining
    the expressions predicted by the language model
    according to the schema. Different to `SchemaConstraintContext`
    this allows the parser to communicate with a neural network
    that can constrain the slot values.

    Parameters
    -----------
    known_slots
        Slots correctly generated by the language model before
        the current turn.
        If the agent is running in optimised mode, these
        slots are not displayed in the constraint prompt.
        Otherwise, this attribute is ignored.
    is_value_object_reference
        Whether the constraint request is for an object property
        accessed to provide a slot value.
    turn_predicted_slots_raw
        Slots predicted at the current turn.
    ignore_keywords_with_failed_value_resolution
        When function keywords values contain references which
        cannot be resolved (eg city=x2.location where x2 is an
        object without a 'location' member), the whole keyword
        is ignored during session update if this flag is `true`
    """

    last_user_turn_service: ServiceName
    schema: CommandCollection
    train_schema: CommandCollection
    dial_id: DialogueID
    agent: SchemaSupervisor
    intent_predicted: bool
    known_slots: tuple[SlotName, ...]
    variable_mapping: dict[VariableIdx, ToolName]
    ignore_keywords_with_failed_value_resolution: bool
    is_value_object_reference: bool = False
    turn_predicted_slots_raw: tuple[str, ...] | None = None


SchemaValidationContext = SchemaConstraintContext | AssistantConstraintContext
