#
# For licensing see accompanying LICENSE file.
# Copyright © 2025 Apple Inc. All Rights Reserved.
#
import logging
import re
from functools import singledispatch
from typing import Any

from pytod.command import (
    CommandCollection,
    ServiceCommand,
    get_all_args,
    get_bool_and_enum_arg_schemas,
)
from pytod.evaluation.helpers import ValueProcessor
from pytod.inference.constraint_prompts import PendingConstraintException
from pytod.inference.constraint_prompts_utils import INVALID_SLOT
from pytod.inference.constraint_request import (
    MemorisationInfo,
    SlotConstraintRequest,
    ValueConstraintRequest,
)
from pytod.inference.utils import find_closest_match, map_tool_name_to_service_intent
from pytod.interpreter.metadata import (
    ENTITY_SELECTION_TOOL,
    FOLLOWUP_INTENT_TOOL_KWARG,
    INTENT_UPDATE_TOOL,
    PARSE_ERROR_TOOL,
    QUERY_RESULTS_REF_KWARG,
    SPECIAL_KWARGS,
    SPECIAL_TOOLS,
    WILDCARD_VALUE,
)
from pytod.parser.expresion_validation_context import (
    AssistantConstraintContext,
    SchemaConstraintContext,
    SchemaValidationContext,
)
from pytod.parser.expresion_validation_utils import (
    ConstrainedKeyword,
    ParserFeedback,
    contains_object_reference,
    maybe_strip_object_reference,
    parse_error_dict,
)
from pytod.parser.schema_constraint_feedback_utils import (
    _collect_memorisation_feedback,
    _collect_service_argument_feedback,
    _schema_validation_failure_msg,
)
from pytod.pytod_types.aliases import IntentName, ServiceName, ToolName
from pytod.sgd_metadata import multivalue_offered_action_slots
from pytod.utils import snake_case, stringify_list

logger = logging.getLogger(__name__)
FieldName = str  # any field of the Expression class
#  feedback from the parser about the current turn.
#  empty if turn satisfies schema constraints
Feedback = list[str]

CONSTRAINT_SUCCESS_MSG = "KeywordConstraintAssistant mapped: {kwarg_name} -> {result}"
CONSTRAINT_FAILED_MSG = (
    "KeywordConstraintAssistant failed to find any similarity "
    "between '{kwarg_name}' and any slots in the '{service}' schema."
)


def constrain_tool_name(
    data: dict[str, Any], context: SchemaConstraintContext
) -> tuple[FieldName, list[str]] | None:
    """Ensure that:

    - the predicted service is part of the schema
    - the function calls generated by the model is a valid intent
    in the current schema
    """

    feedback = []
    tool_name = data["tool"]
    if tool_name in SPECIAL_TOOLS or not isinstance(context, SchemaValidationContext):
        return
    service, intent = map_tool_name_to_service_intent(tool_name)
    schema = context.schema
    if service not in schema.services or service is None:
        msg = (
            f"Unknown service: {service}"
            if service is not None
            else f"Could not extract service from tool {tool_name}. "
        )
        if context.intent_predicted:
            msg += (
                f"It seems that an intent was already predicted, "
                f"maybe `{tool_name}(...)` is a hallucinated statement?"
            )
            data.update(parse_error_dict())
            feedback.append(msg)
            logger.warning(f"{context.dial_id}: {msg}")
            return "tool", feedback
        feedback.append(msg)
        logger.warning(f"{context.dial_id}: {msg}")
        service = context.last_user_turn_service
    else:
        if service != (expected_service := context.last_user_turn_service):
            msg = (
                f"The wrong service was predicted: {service}. "
                f"Expected: {expected_service}."
            )
            feedback.append(msg)
            logger.warning(f"{context.dial_id}: {msg}")
            service = expected_service
        intent_schema = schema.get(service, intent)
        if intent_schema is None and service is None:
            msg = (
                f"API {snake_case(intent)} is not part of {service} implementation. "
                f"Perhaps the service should be {context.last_user_turn_service}?"
            )
            logger.warning(f"{context.dial_id}: {msg}")
            feedback.append(msg)
            logger.info(f"Setting service to: {context.last_user_turn_service}")
            service = context.last_user_turn_service

    assert service is not None
    possible_tool_names = []
    for command in schema.get_service_commands(service):
        expected_tool_name = command.tool_name
        possible_tool_names.append(expected_tool_name)
        if expected_tool_name == tool_name:
            break
    else:
        closest_matching_tool = find_closest_match(tool_name, possible_tool_names).match
        try:
            assert closest_matching_tool is not None
            data["tool"] = closest_matching_tool
            logger.warning(
                f"{context.dial_id}: Invalid tool name: {tool_name}. "
                f"Changed to {closest_matching_tool}"
            )
        except AssertionError:
            possible_tools_str = stringify_list(possible_tool_names, word="or")
            data.update(parse_error_dict())
            logger.warning(
                f"No match was found for {tool_name} amongst {possible_tools_str}"
            )
        possible_tools_str = stringify_list(possible_tool_names, word="or")
        feedback.append(
            f"Illegal tool name: {tool_name}. Should be one of: {possible_tools_str}."
        )
    if feedback:
        return "tool", feedback
    return


def _maybe_resolve_intent_schema(
    kwarg: str, tool_name: str, context: SchemaValidationContext
) -> ParserFeedback | ServiceCommand | ServiceName:
    """Attempt to resolve `tool_name` to a service and intent so that the
     command schema can be retrieved.

    Parameters
    ----------
    kwarg
        An expression keyword argument name.
    tool_name
        The name of the tool the expression represents.
    context
    """

    feedback = []
    if tool_name == INTENT_UPDATE_TOOL:
        try:
            var_idx = int(kwarg[1 : kwarg.find(".")])
        except ValueError:
            msg = f"Invalid variable name in left-hand side of assignment: {kwarg}."
            logger.warning(f"{context.dial_id}: {msg}")
            feedback.append(msg)
            return ParserFeedback(feedback=feedback)
        try:
            tool_name = context.variable_mapping[var_idx]
        except KeyError:
            msg = (
                f"Variable x{var_idx} is not declared, "
                f"so cannot be used in assignment instructions"
            )
            logger.warning(f"{context.dial_id}: {msg}.")
            feedback.append(msg)
            return ParserFeedback(feedback=feedback)
        service, intent = map_tool_name_to_service_intent(tool_name)
        try:
            assert service is not None
        except AssertionError:
            msg = f"Could not extract service name from tool: {tool_name}. "
            if intent in SPECIAL_TOOLS or intent.endswith("_task"):
                intent = intent.replace("_task", "")
                msg += f"Variables bound to `{intent}` can never be assignment targets."
                feedback.append(msg)
                return ParserFeedback(feedback=feedback)
            feedback.append(msg)
            service = context.last_user_turn_service
    else:
        # we have validated the tool name before, so this should
        # not throw an error
        service, intent = map_tool_name_to_service_intent(tool_name)
        assert service is not None
    intent_schema = context.schema.get(service, intent)
    if intent_schema is None:
        return service
    return intent_schema


@singledispatch
def _get_constraint(
    context: SchemaValidationContext,
    kwarg: str,
    kwarg_value: str,
    tool_name: str,
    service: ServiceName,
    intent: IntentName,
    intent_schema: ServiceCommand | None,
):
    """A generic function that attempts to constrain keyword argument
    (and possibly its value) to schema"""
    raise ValueError(f"Unknown context type: {context.__class__.__name__}")


@_get_constraint.register(SchemaConstraintContext)
def _edit_distance_constraint(
    context: SchemaConstraintContext,
    kwarg: str,
    kwarg_value: str,
    tool_name: str,
    service: ServiceName,
    intent: IntentName,
    intent_schema: ServiceCommand | None,
) -> ParserFeedback:
    """Constrain argument name to be one of the arguments specified
    in the `service` schema or `intent_schema` if sufficiently close to
    one in Levenstein distance.

    Parameters
    ----------
    tool_name
        The name of the tool the model generated.
    kwarg, kwarg_value
        A keyword for the tool - this may be an argument name (time)
        or an attribute access (e.g. x1.time). Similarly, the value can be
        a resolved string or a reference to an object property.
    service, intent
        The service and intent `tool_name` was resolved to.
    intent_schema
        The schema of the current intent. It may be `None` if the intent could not be resolved.
    context
        Information necessary for validation
    """

    kwarg_name = maybe_strip_object_reference(kwarg, tool_name)
    # check if the slot is memorised from a different service
    cmd_collection = context.schema
    feedback = _collect_memorisation_feedback(
        kwarg_name, service, intent, tool_name, context
    )
    # check if the slot is sufficiently close to a slot in the schema
    threshold = context.slot_sim_threshold
    all_args = set()
    for cmd in cmd_collection.get_service_commands(service):
        all_args = all_args.union(get_all_args(cmd))
    cmd_args = set()
    # intent_schema=None if the model tries to assign to a special tool
    if intent_schema is not None:
        cmd_args = get_all_args(intent_schema)
    closest_match = find_closest_match(kwarg_name, list(all_args))
    if closest_match.score >= threshold:
        closest_argument, value_replacement = closest_match.match, None
        # don't replace with other slots from the schema unless really similar
        if (
            closest_match.score < context.schema_slot_sim_threshold
            and closest_match.match not in cmd_args
        ):
            closest_argument = None
        if closest_argument is not None:
            msg = (
                f"Misspelled argument `{kwarg_name}` is similar to `{closest_argument}`"
            )
            logger.info(
                f"Replacing slot {kwarg_name} to obtain kwarg: {closest_argument}"
            )
            closest_argument = kwarg.replace(kwarg_name, closest_argument)
        else:
            logger.info(f"Ignoring argument: {kwarg_name}")
            msg = _schema_validation_failure_msg(kwarg_name, intent_schema)
        if msg and msg not in feedback:
            feedback.append(msg)
            logger.warning(f"{context.dial_id}: {msg}.")
        if closest_argument is not None and closest_argument in kwarg_value:
            value_replacement = kwarg_value.replace(kwarg_name, closest_argument)
        if (closest_argument, value_replacement) == (None, None):
            constraint = None
        else:
            constraint = ConstrainedKeyword(closest_argument, value_replacement)
        return ParserFeedback(
            constraint=constraint,
            feedback=feedback,
        )
    msg = _schema_validation_failure_msg(kwarg_name, intent_schema)
    if msg and msg not in feedback:
        feedback.append(msg)
    return ParserFeedback(feedback=feedback)


def _maybe_queue_request(
    context: AssistantConstraintContext,
    request: SlotConstraintRequest | ValueConstraintRequest,
) -> ConstrainedKeyword | None:
    """Check if a request has been cached by the agent and queue a request otherwise."""
    cached_result = context.agent[request]
    if cached_result is None:
        context.agent.queue_request(context.dial_id, request)
    return cached_result


def get_memorisation_info(
    arg: str, service: ServiceName, train_schema: CommandCollection
) -> MemorisationInfo | None:
    """Return `True` if `arg` appears in the training set in the same domain.

    Parameters
    ----------
    arg, train_schema
    service
        The active service during `arg` predictions.
    """

    arg_services = train_schema.get_arg_services(arg)
    if arg_services is None:
        return None
    if service in arg_services:
        return MemorisationInfo(services=arg_services)
    learned_domains = [s.split("_")[0] for s in arg_services]
    active_domain = service.split("_")[0]
    memorised_services = []
    for i, domain in enumerate(learned_domains):
        if active_domain == domain and (s := arg_services[i]) not in memorised_services:
            memorised_services.append(s)
    if memorised_services:
        memorised_services.sort(key=lambda s: int(s.split("_")[1]))
        return MemorisationInfo(services=memorised_services)
    return None


def mark_as_categorical(
    kwarg_name: str, kwarg_value: str, service: ServiceName, schema: CommandCollection
) -> bool:
    """Mark a hallucinated slot as potentially categorical based on the predicted value."""
    if contains_object_reference(kwarg_value) or not get_bool_and_enum_arg_schemas(
        schema, service
    ):
        return False
    # we do not consider int slots as categorical
    try:
        _ = int(kwarg_value)
        return False
    except ValueError:
        pass
    for key in ValueProcessor.LOWER_TO_SCHEMA_CASE_MAPPING:
        if (
            key == kwarg_value
            or kwarg_value in key
        ):
            if key != kwarg_value:
                logger.info(
                    f"{service}: Marking {kwarg_name} as categorical. "
                    f"{kwarg_value} partly matches {key}"
                )
            return True
    return False


def _maybe_resolve_obj_service(
    kwarg_value: str, context: AssistantConstraintContext, feedback: list[str]
) -> tuple[ServiceName, IntentName] | None:
    """Resolve the service an object referenced in a slot value is a member of."""
    variable, property = kwarg_value.split(".")
    var_index = int(variable[1:])
    turn_idx_to_tool: dict[int, ToolName] = context.variable_mapping
    if var_index not in turn_idx_to_tool:
        feedback += [
            f"Cannot constrain {property} because object reference is invalid. "
            f"Got {variable}"
        ]
        return
    ref_service, ref_intent = map_tool_name_to_service_intent(
        turn_idx_to_tool[var_index]
    )
    try:
        assert ref_service is not None and ref_service in context.schema.services
    except AssertionError:
        feedback += [
            f"Cannot constrain {property} in object reference {kwarg_value} "
            f"because the service {variable} refers to could not be resolved. "
            f"Resolved service: {str(ref_service)}"
        ]
        return
    return ref_service, ref_intent


def _get_value_constraint_request(
    kwarg: str,
    kwarg_request: SlotConstraintRequest,
    kwarg_value: str,
    service: str,
    feedback: list[str],
    context: AssistantConstraintContext,
) -> SlotConstraintRequest | None:
    """Get a request to constrain an object property access in kwarg value."""
    variable, property = kwarg_value.split(".")
    try:
        ref_service, _ = _maybe_resolve_obj_service(kwarg_value, context, feedback)
    # service could not be resolved
    except TypeError:
        logger.warning(
            f"{context.dial_id}: "
            f"Could not resolve object reference service: {kwarg}={kwarg_value}"
        )
        return
    # the hallucination is present both in keyword and keyword value
    # and the service has not changed, then we don't need to call the
    # model again
    if ref_service == service and property == kwarg:
        return kwarg_request

    # a member of the `ref_service` schema is referenced, we
    # do not need to constrain
    if context.schema.in_service_schema(ref_service, property):
        return

    return SlotConstraintRequest.model_validate(
        {
            "service": ref_service,
            "predicted_slot": property,
            "known_slots": tuple(),
            "memorisation_info": get_memorisation_info(
                property, ref_service, context.train_schema
            ),
            "is_value_object_reference": True,
            "categorical": False,
        }
    )


@_get_constraint.register(AssistantConstraintContext)
def _assistant_constraint(
    context: AssistantConstraintContext,
    kwarg: str,
    kwarg_value: str,
    tool_name: str,
    service: ServiceName,
    intent: IntentName,
    intent_schema: ServiceCommand | None,
) -> ParserFeedback:
    """Constrain a keyword and possibly is value to the schema
    definitions by prompting a neural network to map the
    predicted keyword and object references in the value to
    slots defined by the relevant schema."""

    kwarg_name = maybe_strip_object_reference(kwarg, tool_name)
    # check if the slot is memorised from a different service
    feedback = _collect_memorisation_feedback(
        kwarg_name, service, intent, tool_name, context
    )
    obj_ref_value = contains_object_reference(kwarg_value)
    known_slots = context.known_slots
    if (predicted_kwargs := context.turn_predicted_slots_raw) is not None:
        additional = [
            arg
            for arg in predicted_kwargs
            if arg != kwarg_name and context.schema.in_service_schema(service, arg)
        ]
        known_slots += tuple(additional)
    kwarg_request = SlotConstraintRequest.model_validate(
        {
            "service": context.last_user_turn_service,
            "known_slots": known_slots,
            "predicted_slot": kwarg_name,
            "predicted_slot_value": kwarg_value if not obj_ref_value else None,
            "memorisation_info": get_memorisation_info(
                kwarg_name, service, context.train_schema
            ),
            "categorical": mark_as_categorical(
                kwarg_name, kwarg_value, service, context.schema
            ),
        }
    )
    # if we have a single bool|enum argument in the schema, then we ignore known slots so
    # that we don't end up calling the LLM with the same prompt for different slot histories
    if (
        kwarg_request.categorical
        and len(get_bool_and_enum_arg_schemas(context.schema, service)) == 1
    ):
        kwarg_request_dict = kwarg_request.model_dump()
        kwarg_request_dict["known_slots"] = tuple()
        kwarg_request = SlotConstraintRequest.model_validate(kwarg_request_dict)
    kwarg_value_request = None
    if obj_ref_value:
        kwarg_value_request = _get_value_constraint_request(
            kwarg_name, kwarg_request, kwarg_value, service, feedback, context
        )
    constraints: list[ConstrainedKeyword | None] = []
    for r in (kwarg_request, kwarg_value_request):
        if r is not None:
            constraints.append(_maybe_queue_request(context, r))

    dial_id = f"{context.dial_id}"
    match constraints:
        # we have to constrain the slot
        case [None]:
            assert kwarg_value_request is None
            logger.debug(
                f"{dial_id}: Queued keyword constraint request: {str(kwarg_request)}"
            )
            return ParserFeedback(feedback=feedback, pending_constraint=True)
        # constraint was immediately returned from the cache
        case [ConstrainedKeyword(keyword=kwarg_result, value=val)]:
            try:
                assert val is None
            except AssertionError:
                assert kwarg_request.categorical
            assert kwarg_value_request is None
            if kwarg_result == INVALID_SLOT:
                feedback += [
                    CONSTRAINT_FAILED_MSG.format(
                        **{
                            "kwarg_name": kwarg_name,
                            "service": service,
                        }
                    )
                ]
                logger.warning(f"{dial_id}: {feedback[-1]}")
                return ParserFeedback(feedback=feedback)
            constrained_kwarg = kwarg.replace(kwarg_name, kwarg_result)
            feedback += [
                CONSTRAINT_SUCCESS_MSG.format(
                    **{
                        "result": constrained_kwarg,
                        "kwarg_name": kwarg,
                    }
                )
            ]
            logger.warning(f"{dial_id}: {feedback[-1]}")
            return ParserFeedback(
                feedback=feedback,
                constraint=ConstrainedKeyword(constrained_kwarg, val),
            )
        # both keyword and value required constraining but only one could be
        # retrieved from the cache
        case [kwarg_result, kwarg_value_result] if any(v is None for v in constraints):
            if kwarg_result is None:
                logger.debug(
                    f"{dial_id}: Queued keyword constraint request: {str(kwarg_request)}"
                )
            else:
                assert kwarg_value_request is not None, kwarg_value_result is None
                logger.debug(
                    f"{dial_id}: Queued keyword value constraint request:  "
                    f"{str(kwarg_value_request)}"
                )
            return ParserFeedback(feedback=feedback, pending_constraint=True)
        # both keyword and value constraints retrieved from the cache
        case [
            ConstrainedKeyword(keyword=kwarg_result, value=kw_val),
            ConstrainedKeyword(keyword=kwarg_value_result, value=obj_ref_val),
        ]:
            try:
                assert (kw_val, obj_ref_val) == (None, None)
            except AssertionError:
                assert obj_ref_val is None, kw_val is not None
                assert kwarg_request.categorical
            assert not any(v is None for v in constraints)
            match constraints:
                case _ if all(v.keyword == INVALID_SLOT for v in constraints):
                    feedback += [
                        CONSTRAINT_FAILED_MSG.format(
                            **{
                                "kwarg_name": kwarg_name,
                                "service": service,
                            }
                        ),
                        CONSTRAINT_FAILED_MSG.format(
                            **{
                                "kwarg_name": kwarg_value,
                                "service": kwarg_value_request.service,
                            }
                        ),
                    ]
                    for msg in feedback:
                        logger.warning(f"{dial_id}: {msg}")
                    return ParserFeedback(feedback=feedback)
                case _ if any(v.keyword == INVALID_SLOT for v in constraints):
                    if kwarg_value_result == INVALID_SLOT:
                        assert kwarg_result != INVALID_SLOT
                        constrained_kwarg = kwarg.replace(kwarg_name, kwarg_result)
                        feedback += [
                            CONSTRAINT_SUCCESS_MSG.format(
                                **{
                                    "result": constrained_kwarg,
                                    "kwarg_name": kwarg,
                                }
                            ),
                            CONSTRAINT_FAILED_MSG.format(
                                **{
                                    "kwarg_name": kwarg_value,
                                    "service": kwarg_value_request.service,
                                }
                            ),
                        ]
                        for msg in feedback:
                            logger.warning(f"{dial_id}: {msg}")
                        return ParserFeedback(
                            feedback=feedback,
                            constraint=ConstrainedKeyword(constrained_kwarg, None),
                        )
                    feedback += [
                        CONSTRAINT_FAILED_MSG.format(
                            **{
                                "kwarg_name": kwarg_name,
                                "service": service,
                            }
                        ),
                        CONSTRAINT_SUCCESS_MSG.format(
                            **{
                                "result": kwarg_value.replace(
                                    kwarg_value.split(".")[1], kwarg_value_result
                                ),
                                "kwarg_name": kwarg_value,
                            }
                        ),
                    ]
                    for msg in feedback:
                        logger.warning(f"{dial_id}: {msg}")
                    return ParserFeedback(feedback=feedback)
                case _:
                    constrained_kwarg = kwarg.replace(kwarg_name, kwarg_result)
                    constrained_value = kwarg_value.replace(
                        kwarg_value.split(".")[1], kwarg_value_result
                    )
                    feedback += [
                        CONSTRAINT_SUCCESS_MSG.format(
                            **{
                                "result": constrained_kwarg,
                                "kwarg_name": kwarg,
                            }
                        ),
                        CONSTRAINT_SUCCESS_MSG.format(
                            **{
                                "result": constrained_value,
                                "kwarg_name": kwarg_value,
                            }
                        ),
                    ]
                    for msg in feedback:
                        logger.info(f"{dial_id}: {msg}")
                    return ParserFeedback(
                        feedback=feedback,
                        constraint=ConstrainedKeyword(
                            constrained_kwarg, constrained_value
                        ),
                    )
        case _:
            raise ValueError(f"Unexpected value for constraints: {constraints}")


def _constrain_arg(
    kwarg: str,
    kwarg_value: str,
    tool_name: ToolName,
    context: SchemaValidationContext,
) -> ParserFeedback:
    """Attempt to constrain `keyword` and possibly its value (`kwarg_value`) to
    be part of the service schema. If constraint is not possible, the argument
    is ignored (ie not displayed in the prompt for next turn prediction)
    """
    kwarg_name = (
        kwarg[kwarg.find(".") + 1 :] if tool_name == INTENT_UPDATE_TOOL else kwarg
    )
    schema_or_feedback = _maybe_resolve_intent_schema(kwarg, tool_name, context)
    if isinstance(schema_or_feedback, ParserFeedback):
        return schema_or_feedback
    try:
        assert isinstance(schema_or_feedback, ServiceCommand)
        intent_schema = schema_or_feedback
        service, intent = schema_or_feedback.service, schema_or_feedback.name
    except AssertionError:
        assert isinstance(schema_or_feedback, str)
        service, intent, intent_schema = schema_or_feedback, None, None
    # constraining to service schema rather intent because the
    # intent can be wrong but the model could still predict
    # the right arguments
    if context.schema.in_service_schema(service, kwarg_name):
        assert intent_schema is not None
        return _collect_service_argument_feedback(
            kwarg_name, kwarg_value, intent_schema, context
        )
    return _get_constraint(
        context, kwarg, kwarg_value, tool_name, service, intent, intent_schema
    )


def _constrain_select_instruction(
    kwarg: str,
    value: str,
    data: dict[str, Any],
    context: SchemaValidationContext,
) -> ParserFeedback:
    """Ensure the keyword arguments for `select` are correct."""

    def validate_results_variable(value: str) -> str | None:
        maybe_null_str = re.sub(r"x[0-9]+", "", value, count=1)
        if maybe_null_str:
            return f"Invalid value for '{QUERY_RESULTS_REF_KWARG}' kwarg: {value}."
        return

    match kwarg:
        case var if var == QUERY_RESULTS_REF_KWARG:
            maybe_msg = validate_results_variable(value)
            if maybe_msg:
                logger.warning(f"{context.dial_id}: {maybe_msg}")
            return ParserFeedback(feedback=[maybe_msg] if maybe_msg else [])
        case _:
            for i, k in enumerate(data["keyword_args"]):
                if k == QUERY_RESULTS_REF_KWARG:
                    maybe_msg = validate_results_variable(data["kwarg_values"][i])
                    if maybe_msg is not None:
                        logger.warning(
                            f"{context.dial_id}:"
                            f"Could not validate {kwarg}. Invalid `from_results` value."
                        )
                        return ParserFeedback(feedback=[maybe_msg])
                    query_var_idx = int(data["kwarg_values"][i][1:])
                    break
            else:
                msg = "Missing keyword argument: `from_results`"
                logger.warning(
                    f"{context.dial_id}: Could not validate `{kwarg}` as a result"
                )
                return ParserFeedback(feedback=[msg])
            try:
                service, intent = map_tool_name_to_service_intent(
                    context.variable_mapping[query_var_idx]
                )
            except KeyError:
                msg = f"Invalid variable reference in `from_results`: x{query_var_idx}"
                logger.warning(f"{context.dial_id}: {msg}")
                return ParserFeedback(feedback=[msg])
            # service will be None if the variable reference points to the wrong tool
            assert service is not None
            return _constrain_entity_name(kwarg, service, context)


def _constrain_entity_name(
    kwarg: str, service: ServiceName, context: SchemaValidationContext
) -> ParserFeedback:
    """For certain services where multiple entities are specified in a single utterance,
    the 'select' statement takes a keyword that identifies the entity. This function provides
    feedback on the correctness of this argument.

    Parameters
    ---------
    kwarg
        A keyword representing an entity name the model has predicted.
    service
        The current service.
    """

    feedback = []
    try:
        expected_slots = multivalue_offered_action_slots[service]
    except KeyError:
        # can happen if the model generates select(movie_name="x", ...)
        # in e.g. Movies_2 where the select() takes the entity as
        # a positional argument
        expected_slots = []
        if service not in context.schema.services:
            msg = f"`{service}` is not a valid service."
            feedback.append(msg)
            logger.warning(f"{context.dial_id}: {msg}")
    if kwarg not in expected_slots:
        msg = f"Invalid argument {kwarg} specified for `select`. "
        if expected_slots:
            match context:
                case SchemaConstraintContext():
                    msg += f"Expected: {expected_slots[0]}"
                case _:
                    request = SlotConstraintRequest.model_validate(
                        {
                            "service": service,
                            "predicted_slot": kwarg,
                            "known_slots": tuple(),
                            "select_kwarg": True,
                        }
                    )
                    cached_result = _maybe_queue_request(context, request)
                    if cached_result is None:
                        logger.debug(
                            f"{context.dial_id}: Queued 'select' entity constraint request: "
                            f"{str(request)}"
                        )
                        return ParserFeedback(
                            feedback=feedback, pending_constraint=True
                        )
                    if cached_result.keyword == INVALID_SLOT:
                        feedback += [
                            CONSTRAINT_FAILED_MSG.format(
                                **{
                                    "kwarg_name": f"{kwarg}(select)",
                                    "service": service,
                                }
                            )
                        ]
                        return ParserFeedback(feedback=feedback)
                    feedback += [
                        CONSTRAINT_SUCCESS_MSG.format(
                            **{
                                "kwarg_name": f"{kwarg}(select)",
                                "result": cached_result.keyword,
                            }
                        )
                    ]
                    assert (
                        cached_result.value is None
                    ), "Value should be 'None' in 'select' keyword constraint"
                    return ParserFeedback(
                        feedback=feedback,
                        constraint=cached_result,
                    )
        else:
            msg += (
                "In this case `select` takes an entity reference "
                "as a positional argument and a reference to the "
                "query command iterator as the value of `from_results`"
            )
        logger.warning(f"{context.dial_id}: {msg}")
        feedback.append(msg)
    return ParserFeedback(feedback=feedback)


def _apply_constraints(
    data: dict[str, Any],
    feedback_info: list[ParserFeedback],
    context: SchemaConstraintContext,
) -> Feedback:
    """Apply the suggested constraints to the raw expression.

    Parameters
    ----------
    data
       A dictionary containing the tool name, args and kwargs for the expression being parsed.
    feedback_info
       The parser feedback, indicating whether the expressions are correct wrt the schema.
    """

    valid_kwargs, valid_values = [], []
    keywords, values = data["keyword_args"], data["kwarg_values"]
    assert len(keywords) == len(values) == len(feedback_info)
    feedback = []
    for kwarg, value, constraint_info in zip(keywords, values, feedback_info):
        if constraint_info.feedback:
            feedback.extend(constraint_info.feedback)
            if constraint_info.constraint is not None:
                keyword = constraint_info.constraint.keyword
                assert keyword is not None
                if keyword not in valid_kwargs:
                    logger.debug(f"Applying constraint: {kwarg} -> {keyword}")
                    valid_kwargs.append(keyword)
                    if (
                        constrained_value := constraint_info.constraint.value
                    ) is not None:
                        logger.debug(
                            f"Applying constraint to value: {value} -> {constrained_value}"
                        )
                        valid_values.append(constrained_value)
                    else:
                        valid_values.append(value)
                else:
                    msg = (
                        f"Skipping replacement `{keyword}` "
                        f"(value: `{value}`) to avoid argument repetition"
                    )
                    logger.warning(f"{context.dial_id}: {msg}")
                    feedback.append(msg)
            else:
                tool = f"`{data['tool']}`" if data["tool"] != INTENT_UPDATE_TOOL else ""
                msg = (
                    f"Expression `{kwarg}={value}` "
                    f"did not pass {tool} schema validation."
                )
                feedback.append(msg)
                logger.warning(f"{context.dial_id}: {msg}")
                # flag set to false when the slot is from the service
                # schema but not the intent schema to tolerate intent
                # errors
                if not constraint_info.ignore_argument:
                    valid_kwargs.append(kwarg)
                    valid_values.append(value)
        else:
            valid_kwargs.append(kwarg)
            valid_values.append(value)
    data["keyword_args"] = valid_kwargs
    data["kwarg_values"] = valid_values
    return feedback


def _maybe_cast_to_parse_error(
    data: dict[str, Any], feedback: list[str], context: SchemaConstraintContext
):
    """The parser casts a prediction to `parse_error` if the model predicted an
    assignment statement using invalid slots.

    Parameters
    ----------
    data
        Tool name and keywords of the expression being parsed.
    feedback
        If empty, the expression being parsed is correct with respect to the schema.
        Otherwise, this contains information about schema constraint violation.
    """
    if not data["keyword_args"] and data["tool"] == INTENT_UPDATE_TOOL:
        assert not data["kwarg_values"]
        msg = (
            "Assignment is not valid with respect to schema "
            "and existing variable definitions."
        )
        if msg not in feedback:
            feedback.append(msg)
        logger.warning(f"{context.dial_id}: {msg}")
        # this essentially leads to the expression being
        # ignored in the output
        data["tool"] = PARSE_ERROR_TOOL


def _collect_parser_feedback(
    data: dict[str, Any],
    context: SchemaValidationContext,
) -> list[ParserFeedback]:
    """Check whether the expression satisfies schema constraints.

    Parameters
    ----------
    data
        Tool name and keywords of the expression being parsed.
    context
        Information required to ascertain whether the schema constraints are
        satisfied.
    """

    feedback = []
    tool_name = data["tool"]
    for kwarg, value in zip(data["keyword_args"], data["kwarg_values"]):
        match kwarg:
            case var if var == FOLLOWUP_INTENT_TOOL_KWARG:
                # NB: FURTHER VALIDATION POSSIBLE
                feedback.append(ParserFeedback())
            case _:
                if tool_name == ENTITY_SELECTION_TOOL:
                    this_keyword_feedback = _constrain_select_instruction(
                        kwarg, value, data, context
                    )
                else:
                    if tool_name not in SPECIAL_TOOLS and kwarg in SPECIAL_KWARGS:
                        msg = f"Illegal argument {kwarg} for {tool_name}"
                        this_keyword_feedback = ParserFeedback(feedback=[msg])
                        feedback.append(this_keyword_feedback)
                        logger.warning(msg)
                        continue
                    this_keyword_feedback = _constrain_arg(
                        kwarg, value, tool_name, context
                    )
                feedback.append(this_keyword_feedback)
    return feedback


def constrain_arguments(
    data: dict[str, Any], context: SchemaValidationContext
) -> tuple[FieldName, list[str]] | None:
    """Ensure the slot names generated by the model are part of the API schema.
    Collect feedback on memorisation/hallucination by checking whether the arguments
    are from the intent schema.
    """

    if data["tool"] in SPECIAL_TOOLS.difference(
        {INTENT_UPDATE_TOOL, "select", "suggest"}
    ):
        return
    parser_feedback = _collect_parser_feedback(data, context)
    if any(item.pending_constraint for item in parser_feedback):
        raise PendingConstraintException
    feedback = _apply_constraints(data, parser_feedback, context)

    _maybe_cast_to_parse_error(data, feedback, context)
    if feedback:
        return "keyword_args", feedback
    return


def constrain_value(
    data: dict[str, Any], context: SchemaValidationContext
) -> tuple[FieldName, list[str]] | None:
    """Ensure the values of enum and bool categorical slots
    are mapped to one of the possible values in the schema.

    Notes
    -----
    1. This constraint is only applied when PyTOD predicts
    using assistance from the KeywordConstraintAssistant.
    """

    def preprocess_value(value: str) -> str:
        """Ensure the quotes of values are properly handled."""
        if value in {"true", "false"}:
            return value
        try:
            assert all((value.startswith("'"), value.endswith("'"))) or all(
                (value.startswith('"'), value.endswith('"'))
            )
            return value[1:-1]
        except AssertionError:
            assert value[0] not in {"'", '"'}, value[-1] not in {"'", '"'}
            return value

    if data["tool"] in SPECIAL_TOOLS.difference({INTENT_UPDATE_TOOL}) or isinstance(
        context, SchemaConstraintContext
    ):
        return
    schema, service = context.schema, context.last_user_turn_service
    should_stop_execution = False
    feedback = []
    for i, (kwarg, value) in enumerate(zip(data["keyword_args"], data["kwarg_values"])):
        kwarg_name = maybe_strip_object_reference(kwarg, data["tool"])
        arg_schema = schema.get_arg_schema(service, kwarg_name)
        if arg_schema is None and data["tool"] == INTENT_UPDATE_TOOL:
            msg = (
                f"'{kwarg_name}' is not a member of the {service} schema. "
                "Maybe the model updated a previous intent instead of generating "
                "a function call upon service change?"
            )
            feedback.append(msg)
            logger.warning(msg)
            continue
        if (
            arg_schema.is_categorical
            and arg_schema.data_type in {"enum", "bool"}
            and not contains_object_reference(value)
            and not (
                value.strip("'\"") == WILDCARD_VALUE and arg_schema.accepts_wildcard
            )
        ):
            possible_vals = {v.lower() for v in arg_schema.possible_values}
            value = preprocess_value(value)
            if value not in possible_vals:
                req = ValueConstraintRequest.model_validate(
                    {"service": service, "argument": kwarg_name, "value": value}
                )
                constraint = _maybe_queue_request(context, req)
                if constraint is None:
                    should_stop_execution = True
                    logger.debug(
                        f"Queued value constraint request for {kwarg}={value}: {str(req)}"
                    )
                else:
                    _, constrained_value = constraint
                    data["kwarg_values"][i] = constrained_value
                    feedback.append(
                        f"Constrained value {kwarg}={value} to {kwarg}={constrained_value}"
                    )
    if should_stop_execution:
        raise PendingConstraintException
    if feedback:
        return "keyword_args", feedback
    return


def constrain_value_object_reference(
    data: dict[str, Any], context: SchemaValidationContext
) -> tuple[FieldName, list[str]] | None:
    """Ensure the object properties referenced in slot values
    are members of the referenced schemas.

    Notes
    -----
    1. This constraint is only applied when PyTOD predicts
    using assistance from the KeywordConstraintAssistant.
    """

    if data["tool"] in SPECIAL_TOOLS.difference({INTENT_UPDATE_TOOL}) or isinstance(
        context, SchemaConstraintContext
    ):
        return

    def maybe_omit_keywords(data: dict[str, Any], ignore_positions: list[int]):
        """In-place omit keywords for which the value reference
        could not be resolved."""

        if not ignore_positions:
            return

        valid_kwargs, valid_values = [], []
        for i, (kwarg, value) in enumerate(
            zip(data["keyword_args"], data["kwarg_values"])
        ):
            if i not in ignore_positions:
                valid_kwargs.append(kwarg)
                valid_values.append(value)
        data["keyword_args"] = valid_kwargs
        data["kwarg_values"] = valid_values

    should_stop_execution = False
    feedback, ignored_arg_pos = [], []
    schema = context.schema
    current_service = context.last_user_turn_service
    for i, (kwarg, value) in enumerate(zip(data["keyword_args"], data["kwarg_values"])):
        # if value in kwarg, then this is either a correct reference of we have already dealt
        # with it
        if value is None:
            logger.info(f"{context.dial_id}: Ignoring value None for argument {kwarg}")
            ignored_arg_pos.append(i)
            continue
        if contains_object_reference(value) and value not in kwarg:
            try:
                ref_service, _ = _maybe_resolve_obj_service(value, context, feedback)
                _, property = value.split(".")
                if context.schema.get_arg_schema(ref_service, property) is None:
                    logger.warning(
                        f"{context.dial_id}: Property '{property}' is not a member of "
                        f"'{ref_service}' schema but was referenced in expression "
                        f"'{kwarg}={value}' ({data['tool']})."
                    )
                    memorisation_info = get_memorisation_info(
                        property, ref_service, context.train_schema
                    )
                    if (
                        kwarg == property
                        and (schema.get_arg_schema(current_service, kwarg)) is not None
                    ):
                        memorisation_info = memorisation_info or MemorisationInfo(
                            services=[current_service]
                        )

                    req = SlotConstraintRequest.model_validate(
                        {
                            "service": ref_service,
                            "predicted_slot": property,
                            "known_slots": tuple(),
                            "memorisation_info": memorisation_info,
                            "is_value_object_reference": True,
                            "categorical": False,
                        }
                    )
                    constraint = _maybe_queue_request(context, req)
                    if constraint is None:
                        should_stop_execution = True
                        logger.debug(
                            f"Queued value constraint request for {kwarg}={value}: {str(req)}"
                        )
                    else:
                        constrained_slot, val = constraint
                        assert val is None
                        old_value_disp = f"{kwarg}={value}"
                        if constrained_slot == INVALID_SLOT:
                            feedback.append(
                                CONSTRAINT_FAILED_MSG.format(
                                    **{"kwarg_name": property, "service": ref_service}
                                )
                            )
                            msg = (
                                f"{context.dial_id}: Failed to constrain object reference: "
                                f"{old_value_disp} ({data['tool']})."
                            )

                            if context.ignore_keywords_with_failed_value_resolution:
                                msg += " Keyword will be ignored"
                                ignored_arg_pos.append(i)
                            logger.info(msg)
                        else:
                            disp_data = {"kwarg_name": value}
                            value = value.replace(property, constrained_slot)
                            disp_data.update({"result": value})
                            feedback.append(CONSTRAINT_SUCCESS_MSG.format(**disp_data))
                            logger.info(
                                f"{context.dial_id}: "
                                f"Constrained object reference: {old_value_disp} -> {kwarg}={value}"
                            )
                        data["kwarg_values"][i] = value
            except TypeError:
                logger.warning(
                    f"{context.dial_id}: "
                    f"Could not resolve object reference service: {kwarg}={value}"
                )
                continue
    if should_stop_execution:
        raise PendingConstraintException
    maybe_omit_keywords(data, ignored_arg_pos)
    if feedback:
        return "keyword_args", feedback
    return


constrain_tool_name.needs_context = True
constrain_arguments.needs_context = True
constrain_value.needs_context = True
constrain_value_object_reference.needs_context = True
